ignoredBuiltDependencies:
  - unrs-resolver

onlyBuiltDependencies:
  - '@swc/core'
  - core-js
overrides:
  array-includes: npm:@nolyfill/array-includes@latest
  array.prototype.findlastindex: npm:@nolyfill/array.prototype.findlastindex@latest
  array.prototype.flat: npm:@nolyfill/array.prototype.flat@latest
  array.prototype.flatmap: npm:@nolyfill/array.prototype.flatmap@latest
  cssnano: $cssnano
  eslint>chalk: npm:picocolors@^1.1.1
  has: npm:@nolyfill/has@latest
  object.fromentries: npm:@nolyfill/object.fromentries@latest
  object.groupby: npm:@nolyfill/object.groupby@latest
  object.values: npm:@nolyfill/object.values@latest
