name: Test

on: [push, pull_request]

jobs:
  linter:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".node-version"
          check-latest: true
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm run lint
        env:
          CI: true
  build:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".node-version"
          check-latest: true
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm run build
        env:
          CI: true
      - name: upload nightly build (es5)
        uses: actions/upload-artifact@v4
        with:
          name: hv-monsterdb.es5.user.js
          path: dist/hv-monsterdb.es5.user.js
      - name: upload nightly build (es2020)
        uses: actions/upload-artifact@v4
        with:
          name: hv-monsterdb.es2020.user.js
          path: dist/hv-monsterdb.es2020.user.js
      - name: Publish
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          if git log -1 --pretty=%B | grep "^release: [0-9]\+\.[0-9]\+\.[0-9]\+$";
          then
            pnpm publish -r --provenance --access public
          elif git log -1 --pretty=%B | grep "^release: [0-9]\+\.[0-9]\+\.[0-9]\+";
          then
            pnpm publish -r --provenance --access public --tag next
          else
            echo "Not a release, skipping publish"
          fi
        env:
          NPM_CONFIG_PROVENANCE: true
