name: Test

on: [push, pull_request]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install npm -g
    - run: npm install
    - run: |
        npm run lint
      env:
        CI: true
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install npm -g
    - run: npm install
    - run: |
        npm run build
      env:
        CI: true
